In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv("C:\\Users\\vaishnavi potode\\OneDrive\\Desktop\\X_DSAAI_B8-main\\messy_vehicle_sales_data.xls")

In [3]:
df.head(10)

Transaction_ID      Sale_Date Manufacturer    Model  Production_Year  \
0           TXN0     12/07/2021         Ford   ModelX           2017.0   
1           TXN1            NaN         Ford   ModelX           2019.0   
2         TXN2##     12/07/2021          BMW    Civic           2019.0   
3           TXN3  July 12, 2021      Hyundai  Corolla              NaN   
4        TXN4ERR     2021-07-12      Hyundai    Civic           2019.0   
5        TXN5ERR       07-12-21          BMW   ModelX           2015.0   
6           TXN6     2021-07-12      Hyundai      NaN           2015.0   
7        TXN7ERR     2021-07-12       Toyota  Mustang              NaN   
8        TXN8ERR       07-12-21    Toyota###   ModelX           2017.0   
9         TXN9##  July 12, 2021          BMW  Corolla              NaN   

  Vehicle_Type Fuel_Type Engine_Size      Horsepower      Torque  ...  \
0          @@@        ??         NaN          150 hp         NaN  ...   
1          123        ??        2.0L           200HP  280 newton  ...   
2        Sedan    Petrol        3.5L  220 horsepower       300Nm  ...   
3        Coupe       NaN         NaN  220 horsepower  280 newton  ...   
4          SUV  Electric         NaN          150 hp       300Nm  ...   
5          123       NaN         NaN          150 hp      250 Nm  ...   
6          @@@    Diesel         NaN  220 horsepower  280 newton  ...   
7          123        ??         NaN  220 horsepower       300Nm  ...   
8        Sedan       NaN        2.0L           200HP  280 newton  ...   
9          @@@    Petrol         NaN             NaN         NaN  ...   

   Curb_Weight_kg Towing_Capacity_kg Interior_Material Exterior_Color  \
0             NaN             2000.0             Vinyl            Red   
1             NaN             2000.0               NaN           Blue   
2          1800kg             1000.0            Fabric             ??   
3            1500             1000.0            Fabric            NaN   
4             NaN             2000.0           Leather            Red   
5            1500             2000.0             Vinyl             ??   
6          1800kg             1000.0             Vinyl          Green   
7          1800kg             2000.0            Fabric            NaN   
8            1500             2000.0            Fabric            Red   
9            1500             1000.0            Fabric           Blue   

  Number_of_Airbags  Software_Update_Capability Regional_Tax_Rate  \
0               6.0                          No              10.0   
1               4.0                         Yes               NaN   
2               NaN                          No               NaN   
3               8.0                         Yes              10.0   
4               4.0                          No               5.0   
5               8.0                         NaN               NaN   
6               8.0                          No              10.0   
7               6.0                         NaN               NaN   
8               NaN                          No               NaN   
9               8.0                          No               5.0   

  Charging_Infrastructure_Score Tariff_Impact_Pct Consumer_Demand_Index  
0                           NaN               NaN                 999.0  
1                           NaN               5.0                   NaN  
2                           NaN               5.0                 999.0  
3                          70.0             999.0                   NaN  
4                          50.0              15.0                  50.0  
5                          70.0               NaN                  50.0  
6                          70.0               5.0                   NaN  
7                          50.0               NaN                  50.0  
8                          70.0             999.0                  70.0  
9                          50.0              15.0                  70.0  

[10 

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 54 columns):
 #   Column                         Dtype  
---  ------                         -----  
 0   Transaction_ID                 object 
 1   Sale_Date                      object 
 2   Manufacturer                   object 
 3   Model                          object 
 4   Production_Year                float64
 5   Vehicle_Type                   object 
 6   Fuel_Type                      object 
 7   Engine_Size                    object 
 8   Horsepower                     object 
 9   Torque                         object 
 10  Acceleration_0_60mph           float64
 11  Top_Speed                      object 
 12  Fuel_Efficiency                object 
 13  CO2_Emissions                  object 
 14  Price_USD                      object 
 15  Production_Cost_Estimate       float64
 16  Market_Segment                 object 
 17  Region_Sold                    object 
 18  Co

In [5]:
df.isnull().sum()

Transaction_ID                        0
Sale_Date                        399963
Manufacturer                          0
Model                            399971
Production_Year                  333421
Vehicle_Type                          0
Fuel_Type                        333868
Engine_Size                      500803
Horsepower                       499835
Torque                           500348
Acceleration_0_60mph             499757
Top_Speed                        499438
Fuel_Efficiency                  499872
CO2_Emissions                    498603
Price_USD                        500139
Production_Cost_Estimate         501138
Market_Segment                   667529
Region_Sold                      499940
Country_Sold                     499951
Dealer_Name                           0
Customer_Age_Group               667910
Customer_Gender                  667282
Payment_Type                     666137
Financing_Interest_Rate          500127
Trade_In_Value                   666710


# Sale_Date Cleaning

In [6]:
df['Sale_Date'].unique()

array(['12/07/2021', nan, 'July 12, 2021', '2021-07-12', '07-12-21'],
      dtype=object)

In [7]:
df['Sale_Date'].value_counts()

Sale_Date
July 12, 2021    401705
07-12-21         399683
12/07/2021       399439
2021-07-12       399210
Name: count, dtype: int64

In [8]:
df['Sale_Date_clean'] = df['Sale_Date']

In [9]:
df['Sale_Date_clean'] = df['Sale_Date_clean'].astype('string')


In [10]:
df['Sale_Date_clean'].dtype

string[python]

In [11]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace('July', '07', regex=False)
)

In [12]:
df['Sale_Date_clean'].unique()

<StringArray>
['12/07/2021', <NA>, '07 12, 2021', '2021-07-12', '07-12-21']
Length: 5, dtype: string

In [13]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace(',', '', regex=False)
)

In [14]:
df['Sale_Date_clean'].unique()

<StringArray>
['12/07/2021', <NA>, '07 12 2021', '2021-07-12', '07-12-21']
Length: 5, dtype: string

In [15]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace(' ', '-', regex=False)
)

In [16]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace('/', '-', regex=False)
)

In [17]:
df['Sale_Date_clean'].unique()

<StringArray>
['12-07-2021', <NA>, '07-12-2021', '2021-07-12', '07-12-21']
Length: 5, dtype: string

In [18]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace(
        r'^07-12-21$',
        '2021-07-12',
        regex=True
    )
)

In [19]:
df['Sale_Date_clean'].unique()

<StringArray>
['12-07-2021', <NA>, '07-12-2021', '2021-07-12']
Length: 4, dtype: string

In [20]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace(
        r'^07-12-2021$',
        '2021-07-12',
        regex=True
    )
)

In [21]:
df['Sale_Date_clean'].unique()

<StringArray>
['12-07-2021', <NA>, '2021-07-12']
Length: 3, dtype: string

In [22]:
df['Sale_Date_clean'] = (
    df['Sale_Date_clean']
    .str.replace(
        r'^12-07-2021$',
        '2021-07-12',
        regex=True
    )
)

In [23]:
df['Sale_Date_clean'].unique()

<StringArray>
['2021-07-12', <NA>]
Length: 2, dtype: string

In [24]:
df['Sale_Date_clean'].value_counts()

Sale_Date_clean
2021-07-12    1600037
Name: count, dtype: Int64

In [25]:
df['Sale_Date_clean'].isnull().sum()

np.int64(399963)

In [26]:
df['Sale_Date'] = df['Sale_Date_clean']

In [27]:
df.head(6)

Transaction_ID   Sale_Date Manufacturer    Model  Production_Year  \
0           TXN0  2021-07-12         Ford   ModelX           2017.0   
1           TXN1        <NA>         Ford   ModelX           2019.0   
2         TXN2##  2021-07-12          BMW    Civic           2019.0   
3           TXN3  2021-07-12      Hyundai  Corolla              NaN   
4        TXN4ERR  2021-07-12      Hyundai    Civic           2019.0   
5        TXN5ERR  2021-07-12          BMW   ModelX           2015.0   

  Vehicle_Type Fuel_Type Engine_Size      Horsepower      Torque  ...  \
0          @@@        ??         NaN          150 hp         NaN  ...   
1          123        ??        2.0L           200HP  280 newton  ...   
2        Sedan    Petrol        3.5L  220 horsepower       300Nm  ...   
3        Coupe       NaN         NaN  220 horsepower  280 newton  ...   
4          SUV  Electric         NaN          150 hp       300Nm  ...   
5          123       NaN         NaN          150 hp      250 Nm  ...   

   Towing_Capacity_kg Interior_Material Exterior_Color Number_of_Airbags  \
0              2000.0             Vinyl            Red               6.0   
1              2000.0               NaN           Blue               4.0   
2              1000.0            Fabric             ??               NaN   
3              1000.0            Fabric            NaN               8.0   
4              2000.0           Leather            Red               4.0   
5              2000.0             Vinyl             ??               8.0   

  Software_Update_Capability  Regional_Tax_Rate Charging_Infrastructure_Score  \
0                         No               10.0                           NaN   
1                        Yes                NaN                           NaN   
2                         No                NaN                           NaN   
3                        Yes               10.0                          70.0   
4                         No                5.0                          50.0   
5                        NaN                NaN                          70.0   

  Tariff_Impact_Pct Consumer_Demand_Index Sale_Date_clean  
0               NaN                 999.0      2021-07-12  
1               5.0                   NaN            <NA>  
2               5.0                 999.0      2021-07-12  
3             999.0                   NaN      2021-07-12  
4              15.0                  50.0      2021-07-12  
5               NaN                  50.0      2021-07-12  

[6 rows x 55 columns]

In [28]:
df['Sale_Date'] = pd.to_datetime(
    df['Sale_Date'],
    format='%Y-%m-%d',
    errors='coerce'
)

In [29]:
df['Sale_Date'].dtype

dtype('<M8[ns]')

In [30]:
df['Sale_Date'].unique()

<DatetimeArray>
['2021-07-12 00:00:00', 'NaT']
Length: 2, dtype: datetime64[ns]

In [31]:
df['Sale_Date'].value_counts()

Sale_Date
2021-07-12    1600037
Name: count, dtype: int64

In [32]:
df['Sale_Date'].isnull().sum()

np.int64(399963)

In [33]:
# df['Sale_Date'] = pd.to_datetime(
#     df['Sale_Date'],
#     format='%Y-%m-%d',
#     errors='coerce'
# ).dt.date

In [34]:
# df['Sale_Date'].dtype

In [35]:
# df['Sale_Date'].unique()

In [36]:
# df['Sale_Date'].info()

In [37]:
df['Sale_Date'].dtype

dtype('<M8[ns]')

In [38]:
df['Sale_Date'].unique()

<DatetimeArray>
['2021-07-12 00:00:00', 'NaT']
Length: 2, dtype: datetime64[ns]

In [39]:
df['Sale_Date'].value_counts()

Sale_Date
2021-07-12    1600037
Name: count, dtype: int64

# Transaction_ID Cleaning

In [40]:
df['Transaction_ID'].unique()[:40]    

array(['TXN0', 'TXN1', 'TXN2##', 'TXN3', 'TXN4ERR', 'TXN5ERR', 'TXN6',
       'TXN7ERR', 'TXN8ERR', 'TXN9##', 'TXN10##', 'TXN11ERR', 'TXN12##',
       'TXN13', 'TXN14##', 'TXN15##', 'TXN16ERR', 'TXN17', 'TXN18ERR',
       'TXN19', 'TXN20', 'TXN21##', 'TXN22', 'TXN23##', 'TXN24##',
       'TXN25ERR', 'TXN26##', 'TXN27ERR', 'TXN28', 'TXN29ERR', 'TXN30',
       'TXN31', 'TXN32##', 'TXN33', 'TXN34##', 'TXN35', 'TXN36ERR',
       'TXN37##', 'TXN38ERR', 'TXN39##'], dtype=object)

In [41]:
df['Transaction_ID'].value_counts().sum()

np.int64(2000000)

In [42]:
df['Transaction_ID'] = (
    df['Transaction_ID']
    .astype(str)
    .str.replace('##','', regex=False)
    .str.replace('ERR','', regex=False)
)

In [43]:
df['Transaction_ID'].unique()[:40]

array(['TXN0', 'TXN1', 'TXN2', 'TXN3', 'TXN4', 'TXN5', 'TXN6', 'TXN7',
       'TXN8', 'TXN9', 'TXN10', 'TXN11', 'TXN12', 'TXN13', 'TXN14',
       'TXN15', 'TXN16', 'TXN17', 'TXN18', 'TXN19', 'TXN20', 'TXN21',
       'TXN22', 'TXN23', 'TXN24', 'TXN25', 'TXN26', 'TXN27', 'TXN28',
       'TXN29', 'TXN30', 'TXN31', 'TXN32', 'TXN33', 'TXN34', 'TXN35',
       'TXN36', 'TXN37', 'TXN38', 'TXN39'], dtype=object)

# Vehicle_Type Cleaning

In [44]:
df['Vehicle_Type'].unique()

array(['@@@', '123', 'Sedan', 'Coupe', 'SUV', 'Truck'], dtype=object)

In [45]:
df['Vehicle_Type'] = (
    df['Vehicle_Type']
    .replace(['@@@', '123'], np.nan)
)

In [46]:
df['Vehicle_Type'].unique()

array([nan, 'Sedan', 'Coupe', 'SUV', 'Truck'], dtype=object)

In [47]:
df['Vehicle_Type'].isna().sum()

np.int64(666344)

# Horsepower Cleaning

In [48]:
df['Horsepower'].unique()

array(['150 hp', '200HP', '220 horsepower', nan], dtype=object)

In [49]:
df['Horsepower'] = (
    df['Horsepower']
    .astype(str)
    .str.replace(' hp','', regex=False)
    .str.replace('HP','', regex=False)
    .str.replace(' horsepower','', regex=False)
)

In [50]:
df['Horsepower'].unique()

array(['150', '200', '220', 'nan'], dtype=object)

In [51]:
df['Horsepower'] = pd.to_numeric(
    df['Horsepower'],
    errors='coerce'
).astype('Int64')

In [52]:
df['Horsepower'].unique()

<IntegerArray>
[150, 200, 220, <NA>]
Length: 4, dtype: Int64

In [54]:
df['Horsepower'].isna().sum()

np.int64(499835)

# Model Cleaning

In [55]:
df['Model'].unique()

array(['ModelX', 'Civic', 'Corolla', nan, 'Mustang'], dtype=object)

# Fuel_Type Cleaning

In [56]:
df['Fuel_Type'].unique()

array(['??', 'Petrol', nan, 'Electric', 'Diesel', 'Hybrid'], dtype=object)

In [57]:
df['Fuel_Type'].value_counts().sum()

np.int64(1666132)

In [58]:
df['Fuel_Type'].isna().sum()

np.int64(333868)

In [59]:
df['Fuel_Type'] = (
    df['Fuel_Type']
    .replace(['??'], np.nan)
)

In [60]:
df['Fuel_Type'].unique()

array([nan, 'Petrol', 'Electric', 'Diesel', 'Hybrid'], dtype=object)

In [62]:
df['Fuel_Type'].isna().sum()

np.int64(667472)

# Production_Year Cleaning

In [63]:
df['Production_Year'].unique()

array([2017., 2019.,   nan, 2015., 2018., 2016.])

In [64]:
df['Production_Year'].dtype

dtype('float64')

In [65]:
df['Production_Year'] = pd.to_numeric(
    df['Production_Year'],
    errors='coerce'
).astype('Int64')

In [66]:
df['Production_Year'].unique()

<IntegerArray>
[2017, 2019, <NA>, 2015, 2018, 2016]
Length: 6, dtype: Int64

In [67]:
df['Production_Year'].isna().sum()

np.int64(333421)

In [68]:
df.head(10)

Transaction_ID  Sale_Date Manufacturer    Model  Production_Year  \
0           TXN0 2021-07-12         Ford   ModelX             2017   
1           TXN1        NaT         Ford   ModelX             2019   
2           TXN2 2021-07-12          BMW    Civic             2019   
3           TXN3 2021-07-12      Hyundai  Corolla             <NA>   
4           TXN4 2021-07-12      Hyundai    Civic             2019   
5           TXN5 2021-07-12          BMW   ModelX             2015   
6           TXN6 2021-07-12      Hyundai      NaN             2015   
7           TXN7 2021-07-12       Toyota  Mustang             <NA>   
8           TXN8 2021-07-12    Toyota###   ModelX             2017   
9           TXN9 2021-07-12          BMW  Corolla             <NA>   

  Vehicle_Type Fuel_Type Engine_Size  Horsepower      Torque  ...  \
0          NaN       NaN         NaN         150         NaN  ...   
1          NaN       NaN        2.0L         200  280 newton  ...   
2        Sedan    Petrol        3.5L         220       300Nm  ...   
3        Coupe       NaN         NaN         220  280 newton  ...   
4          SUV  Electric         NaN         150       300Nm  ...   
5          NaN       NaN         NaN         150      250 Nm  ...   
6          NaN    Diesel         NaN         220  280 newton  ...   
7          NaN       NaN         NaN         220       300Nm  ...   
8        Sedan       NaN        2.0L         200  280 newton  ...   
9          NaN    Petrol         NaN        <NA>         NaN  ...   

   Towing_Capacity_kg Interior_Material Exterior_Color Number_of_Airbags  \
0              2000.0             Vinyl            Red               6.0   
1              2000.0               NaN           Blue               4.0   
2              1000.0            Fabric             ??               NaN   
3              1000.0            Fabric            NaN               8.0   
4              2000.0           Leather            Red               4.0   
5              2000.0             Vinyl             ??               8.0   
6              1000.0             Vinyl          Green               8.0   
7              2000.0            Fabric            NaN               6.0   
8              2000.0            Fabric            Red               NaN   
9              1000.0            Fabric           Blue               8.0   

  Software_Update_Capability  Regional_Tax_Rate Charging_Infrastructure_Score  \
0                         No               10.0                           NaN   
1                        Yes                NaN                           NaN   
2                         No                NaN                           NaN   
3                        Yes               10.0                          70.0   
4                         No                5.0                          50.0   
5                        NaN                NaN                          70.0   
6                         No               10.0                          70.0   
7                        NaN                NaN                          50.0   
8                         No                NaN                          70.0   
9                         No                5.0                          50.0   

  Tariff_Impact_Pct Consumer_Demand_Index Sale_Date_clean  
0               NaN                 999.0      2021-07-12  
1               5.0                   NaN            <NA>  
2               5.0                 999.0      2021-07-12  
3             999.0                   NaN      2021-07-12  
4              15.0                  50.0      2021-07-12  
5               NaN                  50.0      2021-07-12  
6               5.0                   NaN      2021-07-12  
7               NaN                  50.0      2021-07-12  
8             999.0                  70.0      2021-07-12  
9              15.0                  70.0      2021-07-12  

[10 rows x 55 columns]

# Manufacturer Cleaning

In [69]:
df['Manufacturer'].unique()[:40]

array(['Ford', 'BMW', 'Hyundai', 'Toyota', 'Toyota###', 'Tesla',
       'Ford###', 'Toyota???', 'Hyundai702', 'Hyundai@@@', 'Tesla###',
       'Tesla@@@', 'Hyundai###', 'Tesla515', 'Toyota870', 'BMW@@@',
       'Tesla943', 'Tesla???', 'Hyundai500', 'Toyota819', 'Ford@@@',
       'Toyota@@@', 'BMW###', 'Ford???', 'Toyota102', 'Tesla496',
       'Hyundai985', 'Hyundai131', 'BMW???', 'Hyundai???', 'Tesla266',
       'Tesla261', 'Hyundai160', 'Toyota449', 'Ford762', 'Tesla711',
       'Tesla795', 'Hyundai256', 'BMW861', 'BMW193'], dtype=object)

In [70]:
df['Manufacturer'] = (
    df['Manufacturer']
    .astype(str)
    .str.replace('###','', regex=False)
    .str.replace('@@@','', regex=False)
    .str.replace('???','', regex=False)
)

In [71]:
df['Manufacturer'].unique()[:40]

array(['Ford', 'BMW', 'Hyundai', 'Toyota', 'Tesla', 'Hyundai702',
       'Tesla515', 'Toyota870', 'Tesla943', 'Hyundai500', 'Toyota819',
       'Toyota102', 'Tesla496', 'Hyundai985', 'Hyundai131', 'Tesla266',
       'Tesla261', 'Hyundai160', 'Toyota449', 'Ford762', 'Tesla711',
       'Tesla795', 'Hyundai256', 'BMW861', 'BMW193', 'Toyota333',
       'Ford649', 'Hyundai875', 'Ford908', 'Hyundai994', 'Hyundai746',
       'BMW283', 'Hyundai275', 'Toyota821', 'Ford406', 'Hyundai323',
       'BMW859', 'Ford529', 'Tesla840', 'Hyundai348'], dtype=object)

In [72]:
df['Manufacturer'].value_counts().sum()

np.int64(2000000)

In [73]:
df['Manufacturer'] = (
    df['Manufacturer']
    .astype(str)
    .str.replace(r'\d+$', '', regex=True)
)

In [74]:
df['Manufacturer'].unique()[:40]

array(['Ford', 'BMW', 'Hyundai', 'Toyota', 'Tesla'], dtype=object)

In [75]:
df['Manufacturer'].value_counts().sum()

np.int64(2000000)

In [76]:
df['Manufacturer'].isna().sum()

np.int64(0)

# Engine_Size Cleaning

In [77]:
df['Engine_Size'].value_counts().sum()

np.int64(1499197)

In [78]:
df['Engine_Size'].isna().sum()

np.int64(500803)

In [79]:
df['Engine_Size'].unique()

array([nan, '2.0L', '3.5L', 'ERR'], dtype=object)

In [80]:
df['Engine_Size'].sample(10)

677254     3.5L
1282724     NaN
795251     2.0L
1382399     ERR
1103946     NaN
1214180    2.0L
436862      ERR
1869829     ERR
1248323    3.5L
1406829    2.0L
Name: Engine_Size, dtype: object

In [85]:
df['Engine_Size_clean'] = df['Engine_Size']

In [87]:
df['Engine_Size_clean'] = df['Engine_Size_clean'].replace(
    to_replace=r'^\s*ERR\s*$',
    value=np.nan,
    regex=True
)

In [89]:
df['Engine_Size_clean'].isna().sum()

np.int64(999605)

In [90]:
df['Engine_Size'] = df['Engine_Size_clean']

In [91]:
df['Engine_Size'].isna().sum()

np.int64(999605)

In [92]:
df['Engine_Size'].unique()

array([nan, '2.0L', '3.5L'], dtype=object)

In [93]:
df['Engine_Size'] = (
    df['Engine_Size']
    .astype(str)
    .str.replace('L','', regex=False)
)

In [94]:
df['Engine_Size'].unique()

array(['nan', '2.0', '3.5'], dtype=object)

In [95]:
#Renaming column
df = df.rename(columns={'Engine_Size': 'Engine_Size(L)'})

In [96]:
df['Engine_Size(L)'].unique()

array(['nan', '2.0', '3.5'], dtype=object)

In [99]:
df['Engine_Size(L)'].isna().sum()

np.int64(0)

In [100]:
df['Engine_Size(L)'] = pd.to_numeric(
    df['Engine_Size(L)'],
    errors='coerce'
).astype('float64')

In [101]:
df['Engine_Size(L)'].unique()

array([nan, 2. , 3.5])

In [102]:
df['Engine_Size(L)'].dtype

dtype('float64')

In [103]:
df['Engine_Size(L)'].isna().sum()

np.int64(999605)

# Torque Cleaning

In [104]:
df['Torque'].isna().sum()

np.int64(500348)

In [105]:
df['Torque'].unique()

array([nan, '280 newton', '300Nm', '250 Nm'], dtype=object)

In [106]:
df['Torque'].dtype

dtype('O')

In [107]:
#Renaming column
df = df.rename(columns={'Torque': 'Torque(newton)'})

In [109]:
df['Torque(newton)'].dtype

dtype('O')

In [110]:
df['Torque(newton)'].isna().sum()

np.int64(500348)

In [114]:
df['Torque(newton)'].unique()

array(['nan', '280', '300', '250 '], dtype=object)

In [ ]:
# df['Torque(newton)'] = (
#     df['Torque(newton)']
#     .astype(str)
#     .str.replace(' newton','', regex=False)
#     .str.replace('Nm','', regex=False)
#     .str.replace(' Nm','', regex=False)
# )

In [115]:
df['Torque(newton)'] = (
    df['Torque(newton)']
    .astype(str)
    .str.replace(' ','', regex=False)
)

In [116]:
df['Torque(newton)'].unique()

array(['nan', '280', '300', '250'], dtype=object)

In [117]:
df['Torque(newton)'] = pd.to_numeric(
    df['Torque(newton)'],
    errors='coerce'
).astype('Int64')

In [118]:
df['Torque(newton)'].unique()

<IntegerArray>
[<NA>, 280, 300, 250]
Length: 4, dtype: Int64

In [119]:
df['Torque(newton)'].isna().sum()

np.int64(500348)

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 56 columns):
 #   Column                         Dtype         
---  ------                         -----         
 0   Transaction_ID                 object        
 1   Sale_Date                      datetime64[ns]
 2   Manufacturer                   object        
 3   Model                          object        
 4   Production_Year                Int64         
 5   Vehicle_Type                   object        
 6   Fuel_Type                      object        
 7   Engine_Size(L)                 float64       
 8   Horsepower                     Int64         
 9   Torque(newton)                 Int64         
 10  Acceleration_0_60mph           float64       
 11  Top_Speed                      object        
 12  Fuel_Efficiency                object        
 13  CO2_Emissions                  object        
 14  Price_USD                      object        
 15  Production_Cost